# Generated by Django 6.0.6 on 2026-06-30 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlist',
            options={'verbose_name': 'Вишлист', 'verbose_name_plural': 'Вишлисты'},
        ),
        migrations.AlterModelOptions(
            name='wishlistaccess',
            options={'verbose_name': 'Ручной доступ к вишлисту', 'verbose_name_plural': 'Ручные доступы к вишлистам'},
        ),
        migrations.AlterModelOptions(
            name='wishlistitem',
            options={'verbose_name': 'Предмет вишлиста', 'verbose_name_plural': 'Предметы вишлистов'},
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='allowed_relation_types',
            field=models.JSONField(blank=True, default=list, verbose_name='Типы отношений с доступом'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Публичный'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='wishlistaccess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_accesses', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='wishlistaccess',
            name='wishlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_accesses', to='wishlists.wishlist', verbose_name='Вишлист'),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='wishlist_items/', verbose_name='Загруженное изображение'),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='image_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на изображение'),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='product_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на товар'),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='wishlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='wishlists.wishlist', verbose_name='Вишлист'),
        ),
    ]
